CODES:
  # comm err
  F401:
    status: 401
    message: '登录已经失效，请重新登录！'

  'F401-0':
    status: 401
    message: ''

  'F401-1':
    status: 401
    message: '页面已过期，请关闭后重新再试'

  F402:
    status: 401
    message: '页面停留时间过长，请重新开始'

  F404:
    status: 404
    message: '系统繁忙，请稍后再试！'

  # common biz err start with F49***
  F490005:
    status: 400
    message: '验证码不正确或已过期'

  F490002:
    status: 400
    message: '请求参数错误'

  F490003:
    status: 400
    message: '上传失败'

  # project biz err
